name: app
type: "java:11"
disk: 1024
hooks:
    build: mvn clean package -DskipTests
relationships:
    database: "db:postgresql"
web:
    commands:
        start: java -jar $JAVA_OPTS target/jpa-0.1.jar