name: app
type: "java:11"
disk: 1024
hooks:
    build: mvn clean package -DskipTests
relationships:
    mongodb: 'mongodb:mongodb'
web:
    commands:
        start: java -jar $JAVA_OPTS target/mongodb-0.1.jar